### ISSUE TITLE
zypper 1.14.25 fails to build on Fedora Rawhide (libzypp 17.11.1 & boost 1.69.0)

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/zypper#255]
I'm trying to build zypper 1.14.25 for Fedora Rawhide and it fails quite a lot with errors similar to the following:

```
BUILDSTDERR: In file included from /builddir/build/BUILD/zypper-1.14.25/src/Config.h:21,
BUILDSTDERR:                  from /builddir/build/BUILD/zypper-1.14.25/src/Zypper.h:27,
BUILDSTDERR:                  from /builddir/build/BUILD/zypper-1.14.25/src/callbacks/media.h:19,
BUILDSTDERR:                  from /builddir/build/BUILD/zypper-1.14.25/src/callbacks/media.cc:12:
BUILDSTDERR: /builddir/build/BUILD/zypper-1.14.25/src/output/Out.h: In destructor 'Out::ProgressBar::~ProgressBar()':
BUILDSTDERR: /builddir/build/BUILD/zypper-1.14.25/src/output/Out.h:1008:66: error: cannot convert 'zypp::TriBool' {aka 'boost::logic::tribool'} to 'bool'
BUILDSTDERR:  1008 |     _out.progressEnd( _progressId, outLabel( _progress.name() ), _error );
BUILDSTDERR:       |                                                                  ^~~~~~
BUILDSTDERR:       |                                                                  |
BUILDSTDERR:       |                                                                  zypp::TriBool {aka boost::logic::tribool}
BUILDSTDERR: /builddir/build/BUILD/zypper-1.14.25/src/output/Out.h:767:33: note:   initializing argument 3 of 'virtual void Out::progressEnd(const string&, const string&, bool)'
BUILDSTDERR:   767 |                            bool error = false) = 0; // might be a string with error message instead
BUILDSTDERR:       |                            ~~~~~^~~~~~~~~~~~~
BUILDSTDERR: make[2]: *** [src/CMakeFiles/zypper_lib.dir/build.make:287: src/CMakeFiles/zypper_lib.dir/callbacks/media.cc.o] Error 1
BUILDSTDERR: make[2]: *** Waiting for unfinished jobs....
```

This is happening all over the place, as evidenced by this log: [zypper-1.14.25-1.fc30-scratchbuild.txt](https://github.com/openSUSE/zypper/files/2854223/zypper-1.14.25-1.fc30-scratchbuild.txt)

I'm not sure what's going on here...

**Comment by mlandres** [comment]
Probably due to Boost 1.69 now requiring explicit casts tribool->bool.
